from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import joblib
import pandas as pd
import uvicorn
import os

# Initialize FastAPI app
app = FastAPI(
    title="Iris Data Pipeline API",
    description="API for predicting Iris flower sepal length based on sepal width",
    version="1.0.0"
)

# Configure CORS
origins = [
    "*",  # Allow all origins for development
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Input model
class PredictionInput(BaseModel):
    sepal_width: float

# Load model (mock if not found for development since we don't have the trained model file yet)
model_path = "../data/iris_model.joblib"
# In a real scenario, we would load the model from the volume
# model = joblib.load(model_path) 

# Mock model for demonstration/development if file doesn't exist
# Simple linear-ish approximation based on Iris dataset stats
# sepal_length approx = 6.5 - 0.2 * sepal_width (very rough, just for demo return)
def simple_predict(sepal_width):
    return 3.4 + 0.8 * sepal_width + (hash(str(sepal_width)) % 10) / 20.0 # adding some pseudo-random variation

@app.get("/")
def read_root():
    return {"status": "online", "message": "Iris Data Pipeline API is running"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}

@app.post("/predict")
def predict(input_data: PredictionInput):
    try:
        # In production: prediction = model.predict([[input_data.sepal_width]])[0]
        # Using mock prediction for now as we don't have the model file artifact generated by the pipeline yet
        prediction = simple_predict(input_data.sepal_width)
        
        return {
            "sepal_width": input_data.sepal_width,
            "predicted_sepal_length": round(prediction, 2)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
