FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances système pour psycopg2 (le driver Postgres)
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Au lancement du conteneur, on lance le script
CMD ["python", "datatreatment.py"]